for i in range(1,13):
  print "<section name = \"piece_"+str(i)+"\">"
  print "  <sprite name = \"normal\">"
  print "    <image file = \"piece"+str(i)+"/normal.png\" />"
  print "  </sprite>"
  print "  <sprite name = \"appear\">"
  print "    <image file=\"piece"+str(i)+"/appear.png\">"
  print	"      <grid pos=\"0,0\" size=\"50,50\" />"
  print "	   </image>"
  print "    <image file=\"piece"+str(i)+"/appear.png\">"		      
  print "      <grid pos=\"50,0\" size=\"50,50\" />"
  print "    </image>"
  print "    <image file=\"piece"+str(i)+"/appear.png\">"		      
  print "      <grid pos=\"100,0\" size=\"50,50\" />"
  print "   	</image>"
  print "     <animation speed=\"50\" />"
  print "  </sprite>"   
  print "  <sprite name = \"disappear\">"
  print "    <image file=\"piece"+str(i)+"/disappear.png\">"
  print	"      <grid pos=\"0,0\" size=\"50,50\" />"
  print "	   </image>"
  print "    <image file=\"piece"+str(i)+"/disappear.png\">"		      
  print "      <grid pos=\"50,0\" size=\"50,50\" />"
  print "    </image>"
  print "    <image file=\"piece"+str(i)+"/disappear.png\">"		      
  print "      <grid pos=\"100,0\" size=\"50,50\" />"
  print "   	</image>"
  print "     <animation speed=\"50\" />"
  print "  </sprite> " 
  print "  <sprite name = \"little\">"
  print "    <image file = \"piece"+str(i)+"/little.png\" />"
  print "  </sprite>"  
  print "</section>"
